# Mapeamento para relação entre os produtos e suas categorias
# 51 produtos -> 10 categorias

produto_categoria = {
    'Sapato': 'Moda e Acessórios',
    'Bolsa': 'Moda e Acessórios',
    'Calça': 'Moda e Acessórios',
    'Camisa': 'Moda e Acessórios',
    'Vestido': 'Moda e Acessórios',
    'Perfume': 'Cosméticos e Perfumaria',
    'Creme de Barbear': 'Cosméticos e Perfumaria',
    'Hidratante': 'Cosméticos e Perfumaria',
    'Shampoo': 'Cosméticos e Perfumaria',
    'Protetor Solar': 'Cosméticos e Perfumaria',
    'Geladeira': 'Eletrodomésticos',
    'Fogão': 'Eletrodomésticos',
    'TV': 'Eletrodomésticos',
    'Máquina de Lavar': 'Eletrodomésticos',
    'Máquina de Secar': 'Eletrodomésticos',
    'O Romance Exagerado': 'Livros',
    'Suspense Demais': 'Livros',
    'Terror Aterrorizante': 'Livros',
    'A Comédia Engraçada': 'Livros',
    'A História de SQL': 'Livros',
    'Mouse': 'Informática',
    'Teclado': 'Informática',
    'Pen-Drive': 'Informática',
    'Impressora': 'Informática',
    'HD Externo': 'Informática',
    'Poltrona': 'Casa e Decoração',
    'Almofada': 'Casa e Decoração',
    'Cadeira': 'Casa e Decoração',
    'Sofá': 'Casa e Decoração',
    'Mesa': 'Casa e Decoração',
    'Video-Game': 'Eletrônicos',
    'Máquina Fotográfica': 'Eletrônicos',
    'Notebook': 'Eletrônicos',
    'PC': 'Eletrônicos',
    'Secador de Cabelo': 'Eletrônicos',
    'Chuteira': 'Esporte e Lazer',
    'Tornozeleira': 'Esporte e Lazer',
    'Raquete': 'Esporte e Lazer',
    'Bola': 'Esporte e Lazer',
    'Pebolim': 'Esporte e Lazer',
    'Futebol 2020': 'Brinquedos e Games',
    'Iôiô': 'Brinquedos e Games',
    'Peão': 'Brinquedos e Games',
    'Bey-Blade': 'Brinquedos e Games',
    'Casinha de Boneca': 'Brinquedos e Games',
    'Relógio de Pulso': 'Moda e Acessórios',
    'Base Facial': 'Cosméticos e Perfumaria',
    'Aspirador de Pó': 'Eletrodomésticos',
    'Kindle': 'Eletrônicos',
    'Tênis de Corrida': 'Esporte e Lazer',
    'Boneca Articulada': 'Brinquedos e Games'
}